shellEmulator: true

# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: off

packages:
  - . # 根包自身，让 changesets 把 uni-toolkit 识别为可发布的工作区包
  - playground

overrides:
  "@vue/runtime-core": 3.4.21
  vite: 5.2.8
  vitest: 5.0.0 # vitest@4 需要vite@6+
  vue: 3.4.21

updateConfig:
  ignoreDependencies:
    - vite
    - vue
    - "@vue/runtime-core"
    - "@dcloudio/*"
    - sass
    - vitest
