# 当代码推送到main分支时，自动构建并部署到GitHub Pages
name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  # 允许手动触发工作流
  workflow_dispatch:

# 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

# 确保同时只有一个部署在运行
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # 获取完整历史记录，以便VitePress能够获取git数据

      - name: 安装 Pnpm
        uses: pnpm/action-setup@v6

      - name: 设置 Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.21.0
          cache: pnpm

      - name: 安装依赖
        run: pnpm install

      - name: 构建文档
        run: pnpm run docs:build

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/.vitepress/dist

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
